appName: frontend
namespace: default
replicaCount: 2
image:
  repository: my-frontend
  tag: v1.0.0
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
containerPort: 8080
service:
  port: 80
  type: LoadBalancer

# Thêm values cho cronjob
cronjob:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-container
              image: your-cronjob-image:tag
              command: ["/bin/sh", "-c", "your-command"]
