repositories:
  - name: generic-app
    url: https://xuantu55.github.io/helm-chart-example

releases:
  - name: my-generic-app
    namespace: default
    chart: generic-app/generic-app
    version: 0.1.0
    values:
      - values/generic-app.yaml

  - name: my-app-with-cronjob
    namespace: default
    chart: generic-app/app-with-cronjob
    version: 0.1.0
    values:
      - values/app-with-cronjob.yaml
