repositories:
  - name: generic-app
    url: https://xuantu55.github.io/helm-chart-example

releases:
  - name: generic-app
    namespace: default
    chart: generic-app/generic-app
    version: 0.1.0
    installed: true
    wait: true
    timeout: 600
    atomic: true
    values:
      - values/generic-app/environments/dev/values.yaml
#    hooks:
#      - events: ["prepare", "cleanup"]
#        showlogs: true
#        command: "echo"
#        args: ["{{`{{.Release.Name}}`}}", "{{`{{.Environment.Name}}`}}"]
#    needs:
#      - kube-system/ingress-nginx

  - name: app-with-cronjob
    namespace: default
    chart: generic-app/generic-app
    version: 0.1.0
    installed: true
    wait: true
    timeout: 600
    atomic: true
    values:
      - values/app-with-cronjob/environments/dev/values.yaml
#    needs:
#      - generic-app
