repositories:
- name: generic-app
  url: git+https://github.com/xuantu55/helm-chart-example.git
  oci: false

releases:
  - name: frontend
    namespace: default
    chart: generic-app/charts/generic-app
    values:
      - ./values/frontend-values.yaml
    installed: true
  - name: backend
    namespace: default
    chart: generic-app/charts/generic-app
    values:
      - ./values/backend-values.yaml
    installed: true
#  - name: app-with-cronjob
#    namespace: guestbook
#    chart: ./charts/app-with-cronjob
#    values:
#      - ./values/app-with-cronjob-values.yaml
#    installed: true
