repositories:
  - name: generic-app
    url: https://xuantu55.github.io/helm-chart-example

releases:
  - name: frontend
    namespace: default
    chart: generic-app/generic-app
    version: 0.1.0
    installed: true
    wait: true
    timeout: 600
    atomic: true
    values:
      - values/frontend/dev/values.yaml
    needs:
      - backend

  - name: backend
    namespace: default
    chart: generic-app/generic-app
    version: 0.1.0
    installed: true
    wait: true
    timeout: 600
    atomic: true
    values:
      - values/backend/dev/values.yaml

  - name: app-with-cronjob
    namespace: default
    chart: generic-app/app-with-cronjob
    version: 0.1.0
    installed: true
    wait: true
    timeout: 600
    atomic: true
    values:
      - values/app-with-cronjob/dev/values.yaml
    needs:
      - backend
