repositories:
- name: generic-app
  url: https://github.com/xuantu55/helm-chart-example.git

releases:
  - name: frontend
    namespace: default
#    chart: ./charts/generic-app
    values:
      - ./values/frontend-values.yaml
    installed: true
  - name: backend
    namespace: default
#    chart: ./charts/generic-app
    values:
      - ./values/backend-values.yaml
    installed: true
#  - name: app-with-cronjob
#    namespace: guestbook
#    chart: ./charts/app-with-cronjob
#    values:
#      - ./values/app-with-cronjob-values.yaml
#    installed: true
