repositories:
- name: generic-app
  url: https://xuantu55.github.io/helm-chart-example

releases:
  - name: frontend
    namespace: default
    chart: generic-app/generic-app
    values:
      - ./values/frontend-values.yaml
    installed: true
  - name: backend
    namespace: default
    chart: generic-app/generic-app
    values:
      - ./values/backend-values.yaml
    installed: true
#  - name: app-with-cronjob
#    namespace: guestbook
#    chart: ./charts/app-with-cronjob
#    values:
#      - ./values/app-with-cronjob-values.yaml
#    installed: true
