repositories:
  - name: generic-app
    url: https://xuantu55.github.io/helm-chart-example
  - name: generic-app-cronjob
    url: https://xuantu55.github.io/helm-chart-cronjob

releases:
  - name: frontend
    chart: generic-app/generic-app
    version: 0.1.0
    installed: true
    wait: true
    timeout: 600
    atomic: true
    values:
      - values/frontend/dev/values.yaml
    needs:
      - backend

  - name: backend
    chart: generic-app/generic-app
    version: 0.1.0
    installed: true
    wait: true
    timeout: 600
    atomic: true
    values:
      - values/backend/dev/values.yaml

  - name: app-with-cronjob
    chart: generic-app-cronjob/generic-app-cronjob
    version: 0.1.0
    installed: true
    wait: true
    timeout: 600
    atomic: true
    values:
      - values/app-with-cronjob/dev/values.yaml
    needs:
      - backend
