apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-cronjob
              image: {{ (index .Values.cronjob.jobTemplate.spec.template.spec.containers 0).image }}
              command: {{ (index .Values.cronjob.jobTemplate.spec.template.spec.containers 0).command }}
          restartPolicy: OnFailure
