appName: frontend
namespace: default
replicaCount: 2
image:
  repository: nginx
  tag: latest
resources:
  requests:
    memory: "10Mi"
    cpu: "10m"
  limits:
    memory: "100Mi"
    cpu: "100m"
containerPort: 8080
service:
  port: 80
  type: ClusterIP
