repositories:
  - name: generic-app
    url: https://xuantu55.github.io/helm-chart-example
  - name: generic-app-cronjob
    url: https://xuantu55.github.io/helm-chart-cronjob

releases:
  {{- $enabledApps := env "ARGOCD_ENV_app_enabled" | fromJson }}

  {{- range $appName := $enabledApps }}
  - name: {{ $appName }}
    chart: {{ env "ARGOCD_ENV_chart" | default "generic-app/generic-app" }}
    version: 0.1.0
    installed: true
    wait: true
    timeout: 600
    atomic: true
    values:
      - values/{{ $appName }}/values.yaml
  {{- end }}
