repositories:
  - name: generic-app
    url: https://xuantu55.github.io/helm-chart-example
  - name: generic-app-cronjob
    url: https://xuantu55.github.io/helm-chart-cronjob

releases:
  {{- if env "ARGOCD_ENV_app_enabled" }}
  {{- $enabledApps := env "ARGOCD_ENV_app_enabled" | fromJson }}
  {{- if gt (len $enabledApps) 0 }}

  {{- range $appName := $enabledApps }}
  - name: {{ $appName }}
    chart: {{ env "ARGOCD_ENV_chart" | default "generic-app/generic-app" }}
    version: {{ env "ARGOCD_ENV_version" | default "0.1.0" }}
    installed: true
    wait: true
    timeout: 600
    atomic: true
    values:
      - values/{{ $appName }}/values.yaml
  {{- end }}

  {{- end }}
  {{- end }}
