# Kế thừa tất cả values từ generic-app
custom-app:
  appName: custome-app
  namespace: default
  replicaCount: 1
  image:
    repository: nginx
    tag: latest
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  containerPort: 80
  service:
    port: 80
    type: ClusterIP


# Thêm values cho cronjob
cronjob:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-container
              image: your-cronjob-image:tag
              command: ["/bin/sh", "-c", "your-command"]