appName: backend
namespace: default
replicaCount: 2
image:
  repository: nginx
  tag: lastes
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
containerPort: 3000
service:
  port: 80
  type: ClusterIP
