appName: backend
namespace: default
replicaCount: 3
image:
  repository: nginx
  tag: latest
resources:
  requests:
    memory: "10Mi"
    cpu: "10m"
  limits:
    memory: "100Mi"
    cpu: "100"
containerPort: 3000
service:
  port: 80
  type: ClusterIP
