appName: payment
namespace: default
replicaCount: 2
image:
  repository: nginx
  tag: latest
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
containerPort: 8080
service:
  port: 80
  type: ClusterIP

cronjob:
  schedule: "* * 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox
              image: busybox:latest
              command: ["/bin/sh", "-c", "DONE"]
